import { Routes } from '@angular/router';
import { HomeComponent } from './features/home/home.component';
import { ContactsComponent } from './features/contacts/contacts.component';
import { ServicesComponent } from './features/services/services.component';
import { RoomsComponent } from './features/rooms/rooms.component';
import { GalleryComponent } from './features/gallery/gallery.component';
import { RoomDetailComponent } from './features/rooms/room-detail/room-detail.component';
import { RestaurantComponent } from './features/restaurant/restaurant.component';
import { RestaurantBellagioComponent } from './features/restaurant-bellagio/restaurant-bellagio.component';
import { BellagioWeddingComponent } from './features/bellagio-wedding/bellagio-wedding.component';
import { BellagioConferenceComponent } from './features/bellagio-conference/bellagio-conference.component';
import { FamilyEventsComponent } from './features/family-events/family-events.component';
import { CorporateEventsComponent } from './features/corporate-events/corporate-events.component';
import { ConcertsComponent } from './features/concerts/concerts.component';
import { ConferenceServiceComponent } from './features/conference-service/conference-service.component';
import { BowlingEntertainmentComponent } from './features/bowling-entertainment/bowling-entertainment.component';
import { BowlingComponent } from './features/bowling/bowling.component';
import { TennisCourtComponent } from './features/tennis-court/tennis-court.component';
import { ChildrenAttractionsComponent } from './features/children-attractions/children-attractions.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'rooms', component: RoomsComponent },
  { path: 'rooms/:id', component: RoomDetailComponent },
  { path: 'restaurant', component: RestaurantComponent },
  { path: 'restaurant-bellagio', component: RestaurantBellagioComponent },
  { path: 'bellagio-wedding', component: BellagioWeddingComponent },
  { path: 'bellagio-conference', component: BellagioConferenceComponent },
  { path: 'family-events', component: FamilyEventsComponent },
  { path: 'corporate-events', component: CorporateEventsComponent },
  { path: 'concerts', component: ConcertsComponent },
  { path: 'conference-service', component: ConferenceServiceComponent },
  { path: 'bowling-entertainment', component: BowlingEntertainmentComponent },
  { path: 'bowling', component: BowlingComponent },
  { path: 'tennis-court', component: TennisCourtComponent },
  { path: 'children-attractions', component: ChildrenAttractionsComponent },
  { path: 'services', component: ServicesComponent },
  { path: 'gallery', component: GalleryComponent },
  { path: 'contacts', component: ContactsComponent },
  { path: '**', redirectTo: '' }
];
